project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projeto/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),

]

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/<int:recipe_id>/', views.recipes, name='recipe'),
    path('recipes/category/<int:category_id>/', views.category, name="category"),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=10)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=10)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True
    )
    Author = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.title

recipes/views.py
import datetime
from django.http import Http404
from django.shortcuts import render
from .models import Recipe


name = 'Gabriel Prata'
date = datetime.datetime.now()


def home(request):
    recipes = Recipe.objects.filter(is_published=True).order_by('id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
        'name': name,
        'data': date,
        })


def category(request, category_id):
    recipes = Recipe.objects.filter(
        category__id=category_id,
        is_published=True,
        ).order_by('id')

    if not recipes:
        raise Http404('NONECXISTE')

    category_name = recipes.first().category.name

    return render(request, 'recipes/pages/category.html', context={
        'recipes': recipes,
        'category_name': category_name,
        'name': name,
        'data': date,
        })




def recipes(request, recipe_id):
    recipe = Recipe.objects.filter(
        id=recipe_id,
        is_published=True,
    ).first()
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'name': name,
        'data': date,
    })

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}{{category_name}} |{% endblock title %}


{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
        {% include 'recipes/partials/recipe_item.html' %}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home |{% endblock title %}


{% block content %}
    <div class="main-content main-content-list container">
        {% for recipe in recipes %}
        {% include 'recipes/partials/recipe_item.html' %}
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}


{% block title %}{{recipe.title}} |{% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        {% include 'recipes/partials/recipe_item.html' %}
    </div>
{% endblock content %}

recipes/templates/recipes/partials/head.html
{% load static %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/solid.min.css" integrity="sha512-EvFBzDO3WBynQTyPJI+wLCiV0DFXzOazn6aoy/bGjuIhGCZFh8ObhV/nVgDgL0HZYC34D89REh6DOfeJEWMwgg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/fontawesome.min.css" integrity="sha512-R+xPS2VPCAFvLRy+I4PgbwkWjw1z5B5gNDYgJN5LfzV4gGNeRQyVrY7Uk59rX+c8tzz63j8DeZPLqmXvBxj8pA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/brands.min.css" integrity="sha512-nS1/hdh2b0U8SeA8tlo7QblY6rY6C+MgkZIeRzJQQvMsFfMQFUKp+cgMN2Uuy+OtbQ4RoLMIlO2iF7bIEY3Oyg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">



    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">


recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class ="main-logo" href="{% url 'recipes:home' %}">
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe_item.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <a href="{% url 'recipes:recipe' recipe.id %}"><img src="{{recipe.cover.url}}"></a>
    </div>
    <div class="degrade"></div>
    <div class="recipie-title-container">
        
        <h2 class="recipie-title">
            <a class="title-a" href="{% url 'recipes:recipe' recipe.id %}">
                {{ recipe.title }}
            </a>
        </h2>
        
    </div>
    <div class="recipe-author">
        <span class="recipe-author-item">
            <i class="fas fa-user"></i>
           {{recipe.Author.username}}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{recipe.created_at|date:"d/m/Y"}}
        </span>
        <span class="recipe-author-item">
            <a href="{% url 'recipes:category' recipe.category_id %}">
                <i class="fas fa-layer-group"></i>
                <span>{{recipe.category.name}}</span>
            </a>
        </span>
    </div>
    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">
                {{ recipe.preparation_time }} {{ recipe.preparation_time_unit }}
            </div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">
                {{ recipe.servings }} {{ recipe.servings_unit }}
            </div>
        </div>
    </div>
    <div class="recipe-recipe-details">
        <div class="recipe-recipe-details-div">
            <h3>{{ recipe.title }}<br><br></h3>
            {% if recipe.preparation_steps_is_html is True %}
                <p>{{ recipe.preparation_steps | safe }}</p>
            {% else %}
                <p>{{ recipe.preparation_steps | linebreaksbr }}</p>
            {% endif %}
        </div>
    </div>
    <footer class="recipe-footer">
        <a class="recipe-read-more button button-dark button-full-width" href="{% url 'recipes:recipe' recipe.id %}">
            <i class="fas fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" name="search" placeholder="Search for a recipe">
            <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
    </div>
</div>